### ISSUE TITLE
popup toolbar stem styling is square on iOS devices

### ISSUE THREAD

**Issue by jywarren** [Leaflet/Leaflet.toolbar#16]
![mk2-ipad](https://cloud.githubusercontent.com/assets/24359/5928530/f8734794-a649-11e4-8319-25f580bea4be.jpg)

**Comment by manleyjster** [comment]
Hmmm. I'm not able to reproduce this using Chrome's device simulator.

@kyletolle - you had the same square pointer in the images you posted with earlier issues. What was your setup for those images (browser, device, etc)?

**Comment by kyletolle** [comment]
This happens for me when on the current [demo](http://leaflet.github.io/Leaflet.toolbar/examples/popup.html) page using Safari8.0.3 on my MBP running OS X 10.10.2.

**Comment by kyletolle** [comment]
Also when zooming, the popup doesn't follow the feature it's for:
![screenshot 2015-01-29 13 00 38](https://cloud.githubusercontent.com/assets/260869/5965134/e597b8ee-a7b6-11e4-94b1-fa8e7d5ed812.png)

**Comment by manleyjster** [comment]
Ok, thanks guys.

Identified the issue - it's a simple fix: just need to add browser prefixes in front of the `transform` directive in [`Toolbar.less`](https://github.com/Leaflet/Leaflet.toolbar/blob/master/src/Toolbar.less#L66). Will fix this when I get back in front of a computer.

@kyletolle - The second issue that you identified with the popup not moving on zoom is a separate issue introduced by the fix for https://github.com/Leaflet/Leaflet.toolbar/issues/9. I'm opening another issue for that.

**Comment by kyletolle** [comment]
Thanks in advance for fixing!
