### ISSUE TITLE
Popup toolbars are not closed when you open another one

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet.toolbar#3]
![image](https://cloud.githubusercontent.com/assets/25395/5681787/2cb9d2cc-9824-11e4-8de3-5b286fb1b9a0.png)

I suggest doing it like Leaflet: closing an opened toolbar popup when you open another one.

**Comment by manleyjster** [comment]
Yup - I've thought about this, and I agree this is undesirable behavior.

I've been of two minds about whether Leaflet.Toolbar code or application code should fix it.

`L.Toolbar#addTo` is overloaded to accept any number of arguments (see [this post](http://justinmanley.io/blog#overloaded-addto-method-and-_getactionconstructor)). The only special argument is the first argument to `#addTo`, which `Leaflet.Toolbar` assumes to be the map.  This means it would be totally possible to add a few lines of code to ensure that there is only ever a single toolbar on the map.

If, on the other hand, we want to allow multiple toolbars on the map, but only one per feature - that's something that needs to be handled by libraries like `Leaflet.draw` that extend `Leaflet.Toolbar` to create their own toolbars.

I'm going to go ahead now and assume the first case - that we only ever want a single toolbar on the map - and add a bugfix.

**Comment by mourner** [comment]
Sounds good! I can't think of a case where you would want two popup toolbars to be opened.

**Comment by jywarren** [comment]
I've implemented a quick-and-dirty application-side solution in https://github.com/publiclab/Leaflet.DistortableImage/blob/master/examples/select.html#L58

I concur with mourner that I can't think of a situation where you'd want more than one toolbar per map. Would be very happy to adopt a new version which manages that itself. Thanks, Justin!

**Comment by kyletolle** [comment]
I agree that only one toolbar per map would be best.

I'd go a step further and make the popup disappear when the person clicks on the map. Right now, there's no way to dismiss the popup once you've brought it up, unless you click on one of the actions.

**Comment by jywarren** [comment]
+1 for clicking on the map -- I am working on implementing this in Leaflet.Dis

**Comment by jywarren** [comment]
Sorry, mobile Github interface...

...Leaflet.DistortableImage, but have the problem that click events
propagate from the toolbar down to the map:
https://github.com/Leaflet/Leaflet.toolbar/issues/7

**Comment by manleyjster** [comment]
Working on both of these issues - will hopefully get a chance to work on it and push some code tomorrow afternoon.  Thanks for all the input, guys.

**Comment by manleyjster** [comment]
Came up with a solution to this issue - code is in the [single-toolbar-on-map](https://github.com/Leaflet/Leaflet.toolbar/tree/single-toolbar-on-map) branch.

I'm going to let it sit for a few days before merging it into master, bc there are some changes which may be controversial, and I want to give interested folks a chance to take a look at the code and weigh the pros / cons.

This fix allows multiple toolbars on the map, but it only permits one toolbar of each type (i.e. one for each distinct toolbar class). That is, app developers would be able to add multiple control-style toolbars to the map, as long as each derives from a distinct class - for example, DrawControl, LayerControl, and ImageOverlayControl toolbars (each deriving from a corresponding class deriving from L.toolbar.Control). I believe this is a common-enough use-case that it should be supported.

The most controversial feature of this fix is that I override `L.Class.extend` for all classes inheriting from `L.Toolbar`. The purpose of this is to give each of these classes a unique identifier so that each toolbar can be matched to the class from which it is derived.

**Comment by jywarren** [comment]
I like this, but I'm probably not the audience that'd find that controversial. Also, I was considering a similar class-derived unique id approach to the multiple-selected-images issue -- that selecting an image should, without the need for a new global array to track image instances, deselect all others as a default behavior, by checking the class of each item in the map._layers array. So I like the approach.

**Comment by mourner** [comment]
@manleyjster overriding `L.Toolbar.extend` is perfectly fine. Looks like a good fix to me.

**Comment by kyletolle** [comment]
I'd have to experiment with this in use to see if that's the kind of editing I would expect.

Would the new names be more consistent if they were `_toolbarType` and `_toolbarClassId`?

Think it'd be possible for someone to still enforce a policy of "only one toolbar on the map, regardless of class"?
