### ISSUE TITLE
Examples are broken on master

### ISSUE THREAD

**Issue by kyletolle** [Leaflet/Leaflet.toolbar#8]
I've cloned the Leaflet.toolbar repo, am on the master branch, and done an `npm install` like the README instructs. However, when I view the examples (popup and control) in my browser (Safari 8.0.2 on Yosemite), neither of them works.

The popup example gives me this error: `TypeError: undefined is not an object (evaluating 'L.Edit.Popup.Edit')`

The control example gives me errors about loading CDN'd CSS and JS files, as well as this error: `TypeError: undefined is not an object (evaluating 'new L.DrawToolbar.Control')`

Now, if I check out the `gh-pages` branch, the examples do work. But to have the examples broken on the master branch ends up being confusing. And it's not evident that I need to check out `gh-pages` to get working examples.

Could the master branch examples be updated to work?

**Comment by kyletolle** [comment]
Further, if I try to implement the popup example myself by following the steps on the [Building custom toolbars](https://github.com/leaflet/Leaflet.Toolbar/wiki/Building-custom-toolbars) wiki page while using the master branch's `dist/Leaflet.Toolbar.js`, things just don't seem to work.

You can see an example in [my gist](https://gist.github.com/kyletolle/a06062dcf103167be0ef). And a demo at the [bl.ocks.org demo site](http://bl.ocks.org/kyletolle/a06062dcf103167be0ef).

(Each of the css and js files was taken from that repo's respective master branch.)

I get the error `TypeError: undefined is not a function (evaluating 'action._createIcon(this, this._ul, this._arguments)')`.

This seems to be evidence that Leaflet.toolbar's master branch is broken.

---

I've also tried doing `npm install leaflet`, `npm install leaflet-toolbar`, and `npm install leaflet-draw` and using the css and js from the `node_modules` in my [index.html](https://gist.github.com/kyletolle/fcbe93050c6e52050f7a), but things are still broken. I continue to get the error: `TypeError: undefined is not a function (evaluating 'action._createIcon(this, this._ul, this._arguments)')`.

---

All in all, I'm not able to get an example using Leaflet.toolbar and Leaflet.draw working at all. Something's special about that `gh-pages` branch, but I'm not really sure what. I hope my information helps lead to a fix. I'd love to be able to use leaflet, toolbar, and draw for using the popups in my application, once it's back to working!

**Comment by manleyjster** [comment]
Hey Kyle - sorry about this. I understand that it's not intuitive behavior.

The examples for Leaflet.toolbar all draw on Leaflet.draw, which is a separate Leaflet plugin. Leaflet.draw currently uses its own toolbars, not built using Leaflet.toolbar. For this reason, the Leaflet.draw dependency in the Leaflet.toolbar `package.json` file actually points to a feature branch of my own fork of `Leaflet.draw`: [`manleyjster/Leaflet.draw`](https://github.com/manleyjster/Leaflet.draw/tree/leaflet-toolbar-plugin).

The examples page loads the `dist` files for `Leaflet.draw` (that is, `dist/leaflet.draw.js` and `dist/leaflet.draw.css` in the `Leaflet.draw` repo). @jacobtoye has asked me not to include those `dist` files in previous PR's, so, unfortunately, when you `npm install` `Leaflet.toolbar`, those files don't reflect my additions to Leaflet.draw.

This should be resolved once the PR is accepted and we push a new release of `Leaflet.draw`.

In the meantime, the easiest solution for you is just to build `Leaflet.draw` from source after you install `Leaflet.toolbar`.  In the root of `Leaflet.toolbar`, run: `cd node_modules/leaflet-draw && jake build`.

Again, sorry about this - I may modify the files that are loaded in the example so that `Leaflet.draw/src` is loaded, rather than the (out-of-date) files from `Leaflet.draw/dist`.

**Comment by kyletolle** [comment]
Thanks for the quick response @manleyjster! No need to apologize. I had no idea I was attempting to use Leaflet.toolbar and Leaflet.draw together at a time of transition. Very exciting to see this change that's coming!

I knew that Leaflet.draw was a different library, but I naively assumed that Leaflet.toolbar just overrode  or plugged into Leaflet.draw. I'm quite new to Leaflet and its plugins, so it's been a learning experience.

I appreciate the extra information. I now see the `package.json` pointing to your branch of the Leaflet.draw plugin. And it also makes sense as to why things weren't working for me. On the gh-pages branch, it seems you've committed some files under node_modules, which I'm guessing include your modified Leaflet.draw.

Great, I'll see what I can do with building from source. I might also focus on some other pieces of my application for now, until these Leaflet.draw and Leaflet.toolbar modifications are officially released. I've also taken some time to read up on the PR, and your blog post for the work you've done.

I'm certainly excited to use this code, so I look forward to its release!

**Comment by kyletolle** [comment]
Your instructions to build the leaflet-draw source worked to get the popup example working locally on the master branch. Thanks!

**Comment by cyrilchapon** [comment]
The version of the file used in example ([here](http://leaflet.github.io/Leaflet.toolbar/node_modules/leaflet-draw/dist/leaflet.draw-src.js)) doesn't exist at all in your fork repository neither in [leaflet-toolbar](https://github.com/justinmanley/Leaflet.draw/commits/leaflet-toolbar/dist/leaflet.draw-src.js) or [leaflet-toolbar-plugin](https://github.com/justinmanley/Leaflet.draw/blob/leaflet-toolbar-plugin/dist/leaflet.draw-src.js) or [leaflet-toolbar-plugin-patches](https://github.com/justinmanley/Leaflet.draw/commits/leaflet-toolbar-plugin-patches/dist/leaflet.draw-src.js) or even [external-leaflet-toolbar](https://github.com/justinmanley/Leaflet.draw/commits/external-leaflet-toolbar/dist/leaflet.draw-src.js).

None of the latest versions of those branches actually work.

**Comment by justinmanley** [comment]
Marking as fixed because the workaround described in this bug is no longer required with the release of https://github.com/justinmanley/leaflet-draw-toolbar.
